"""Updated name column

Revision ID: 814103810465
Revises: dc9a6a7c6ca0
Create Date: 2024-10-01 10:50:02.780034

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '814103810465'
down_revision = 'dc9a6a7c6ca0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'username',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'username',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
    # ### end Alembic commands ###
